# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-schema-viewer
  version: "0.5.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_schema_viewer-${{ version }}.tar.gz
  sha256: d5bdaa7cfec0827d1232f1d79f746ea5a7f42bf6abf2359615084acb230b2d1c

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=4.0

tests:
  - python:
      imports:
        - schema_viewer
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Visualizes a DB schema based on Django models.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/pikhovkin/django-schema-viewer
  repository: https://github.com/pikhovkin/django-schema-viewer
  documentation: https://django-schema-viewer.up.railway.app/schema-viewer

extra:
  recipe-maintainers:
    - rxm7706
